example/index.html, gulpfile.js, src/css/control-panel.styl, src/css/dependences.styl, src/css/layout.styl, src/css/main.styl, src/css/variables/color.styl, src/js/Tour/defaultOption.js
[Сверсатать навигацию по плееру](https://github.com/Tour-360/tour-player/issues/19)
=> сверстал панель навигации

src/css/control-panel.styl
=> Поправил баг скрытия progress-bar

example/index.html, src/css/dependences.styl, src/css/layout.styl, src/css/markers.styl, src/css/notification.styl, src/css/variables/color.styl
https://github.com/Tour-360/tour-player/issues/32
=> Плашка уведомлений

example/index.html, src/css/layout.styl, src/css/markers.styl, src/css/variables/common.styl, src/js/UI/Marker.js
=> Реализовал title для маркеров

src/img/markers/down.svg, src/img/markers/left.svg, src/img/markers/right.svg, src/img/markers/up.svg
=> Поправил углы иконок маркеров

example/index.html, src/js/UI/notification.js
=> Сделал js реализацию notification

src/css/markers.styl, src/js/UI/Marker.js
=> Исправил ряд ошибок с маркерами

src/js/UI/Marker.js
=> Исправил баг с marker.title

src/css/dependences.styl, src/css/links.styl, src/css/variables/color.styl
=> Определил стиль ссылкам

src/css/layout.styl
=> Запретил перетаскивание для renderer

example/manifest.json, gulpfile.js, src/css/layout.styl, src/js/Tour/Marker.js, src/js/Tour/render.js, src/js/Tour/setMarkers.js, src/js/Tour/setPanorama.js
=> Добавил возможность переключатся между панорамами с помощью маркеров

.gitignore
=> Добавил build/ в .gitignore

src/img/controls/zoom_in.svg, src/img/controls/zoom_out.svg
=> Перерисовал иконки масштабирования

src/js/Tour/keyEvents.js
=> Добавил возможность сохранять скриншоты тура Ctrl+S

example/manifest.json, src/js/Tour/addEventListeners.js, src/js/Tour/history.js, src/js/Tour/init.js, src/js/Tour/mouseEvents.js, src/js/Tour/setMarkers.js, src/js/Tour/setPanorama.js, src/js/Tour/view.js
=> Добавил возможность гулять по истории

src/css/control-panel.styl, src/css/dependences.styl, src/css/mouse-menu.styl, src/css/variables/color.styl, src/css/variables/common.styl, src/js/UI/mouseMenu.js
=> Сверстал mouseMenu

src/js/Tour.js, src/js/Tour/controls.js, src/js/Tour/dictionary.js, src/js/Tour/init.js, src/js/Tour/keyEvents.js, src/js/Tour/setMouseMenu.js
=> Добавил возможность управлять туром из меню мыши

src/js/Tour/init.js, src/js/Tour/view.js
=> Поправил баг и историей

src/js/Tour/addEventListeners.js
=> Поправил баг с DragAndDrop

src/js/Tour/history.js, src/js/Tour/init.js
feat #77
Название тура[ — Название панорамы]
=> Сделал название вкладки составным

src/js/Tour/controls.js, src/js/Tour/dictionary.js, src/js/Tour/init.js
=> Добавил возможность копировать код для вставки

src/js/Tour/ImageLoader.js, src/js/Tour/LoadingManager.js, src/js/Tour/dictionary.js, src/js/Tour/setPlane.js, src/js/Tour/setTexture.js, src/js/UI/controlPanal.js
feat #53 
* Добавил определение состояния загрузки изображений
* Изменяю ```document.body.class``` на ```transition``` Когда панорама загружается 
* Добавил оповещения об ошибках загрузки
=> Сделал отображение загрузки в progressBar

src/css/cursors.styl
=> Курсор прогресса при body.load

src/css/control-panel.styl
=> Поправил анимацию progress-bar

src/js/Tour/controls.js, src/js/Tour/dictionary.js, src/js/Tour/load.js, src/js/Tour/log.js
=> Добавил уведомления о статусе тура, убрал Tour.log

src/js/Tour/addEventListeners.js, src/js/Tour/report.js
=> Добавил отправление отчетов при ошибках

src/css/dependences.styl, src/css/layout.styl, src/css/transition.styl
=> Добавил стили для плавного перехода между панорам

example/manifest.json, src/js/Tour/Marker.js, src/js/Tour/animate.js, src/js/Tour/createScene.js, src/js/Tour/mouseEvents.js
=> Развернул камеру

gulpfile.js
=> Настроил деплой в beta.*

src/js/Tour/defaultOption.js, src/js/Tour/getRenderer.js
=> Поправил getRenderer()

app.json, index.js, package.json
=> Настроил Heroku

example/manifest.json, src/css/background-image.styl, src/css/dependences.styl, src/css/layout.styl, src/js/Tour/backgroundImage.js, src/js/Tour/init.js, src/js/Tour/render.js, src/js/Tour/setPanorama.js, src/js/Tour/setRenderer.js, src/js/Tour/setTexture.js
=> Убрал мелькание при переходах

src/css/mouse-menu.styl, src/js/Tour/controls.js, src/js/UI/mouseMenu.js, src/js/UI/notification.js
=> Поправил меню мыши на FF

src/js/UI/mouseMenu.js
=> Добавил обработчик события window.onblur на закрытие окна

src/js/UI/controlPanal.js
=> Поправил иконки кнопок управления на IE11

src/js/Tour/controls.js
=> Инвертировал кнопки вращения

src/js/Tour/addEventListeners.js, src/js/Tour/mouseEvents.js
=> Сделал плавное масштабирование на MacOS

src/js/UI/mouseMenu.js
=> Добавил возможность выбора пункта меню мыши ПКМ

src/js/Tour/mouseEvents.js
=> Отключил нажатие колеса мыши

gulpfile.js, package.json, src/js/Tour.js
=> Поправил путь выгружаемой сборки

example/index.html, src/css/layout.styl, src/js/Tour/backgroundImage.js, src/js/Tour/createScene.js, src/js/Tour/defaultOption.js, src/js/Tour/init.js, src/js/Tour/mouseEvents.js, src/js/Tour/setControlPanel.js, src/js/Tour/setMouseMenu.js, src/js/Tour/setPanorama.js, src/js/Tour/setTexture.js, src/js/UI/controlPanal.js
=> Добавил функционал 

src/js/Tour/animate.js
=> Инвертировал авто вращение

src/js/Tour/animate.js, src/js/Tour/defaultOption.js
fix #147
https://github.com/Tour-360/tour-player/wiki/%D0%9E%D0%B1%D1%8A%D0%B5%D0%BA%D1%82%D1%8B-%D0%B8-%D0%BC%D0%B5%D1%82%D0%BE%D0%B4%D1%8B
=> Поправил скорость автоматического вращения

example/index.html, src/js/Tour/events.js
=> Поправил eventEmiter

src/js/Tour/mouseEvents.js
=> Заменил screenX на clientX

src/js/Tour/createScene.js, src/js/Tour/init.js, src/js/Tour/setTexture.js
=> Убрал ошибку с undefinedRender

src/js/Tour/init.js, src/js/Tour/load.js, src/js/Tour/setMarkers.js
=> Поправил метод Tour.load()

src/js/Tour/animate.js
=> Добавил автоматический поворот камеры на горизонт, при автовращении

src/js/Tour/setMarkers.js, src/js/Tour/setPanorama.js
feat #164
Добавил в документацию
https://github.com/Tour-360/tour-player/wiki/%D0%A4%D0%BE%D1%80%D0%BC%D0%B0%D1%82-%D1%84%D0%B0%D0%B9%D0%BB%D0%B0-manifest.json
=> Добавил поддержку autorotation в manifest.json

src/js/Tour/Transition.js, src/js/Tour/view.js
=> Добавил ограничение, чтобы в url не было значений больше 360 градусов

src/js/Tour/defaultOption.js, src/js/Tour/mouseEvents.js
=> Переименовал свойство mobileDrag в touchDrag

src/js/Tour/view.js
TypeError: Cannot set property 'auto' of undefined
=> fix поправил ошибку с автовращением

src/js/Tour/getRenderer.js
=> Поправил отображение виртуального тура на мобильных устройствах Apple

src/js/UI/Marker.js
=> fix #102 Поправил баг на IE11 с убиранием маркеров

src/js/Tour/addEventListeners.js, src/js/Tour/mouseEvents.js
=> fix #136 Поправил кинетическое вращение на IE и FF

src/js/Tour/dictionary.js
=> feat #190: Добавил китайский язык

example/index.html, gulpfile.js, src/css/popups.styl
=> feat #194: Перенес деплой на основной сайт

src/css/gallery.styl, src/css/layout.styl
Reverts Tour-360/tour-player#275
=> Revert "Оптимизация скролла для apple"

src/css/control-panel.styl, src/css/mouse-menu.styl
+ Исправлен селектор для backdrop-filter для safari
+ Добавлен backdrop-filter для контекстного меню
=> Fix control-panel on Safari

src/css/markers.styl, src/js/Tour/Marker.js, src/js/UI/Marker.js
https://github.com/Tour-360/tour-player/issues/371
=> Добавил поворот маркеров вместе с наклоном камеры
